export const RESET_CRUD_CHARGER_UPDATE = 'RESET_CRUD_CHARGER_UPDATE';
export const RESET_MODAL_CRUD_CHARGER_UPDATE =
  'RESET_MODAL_CRUD_CHARGER_UPDATE';

/* (ASYNC) */
export const UPDATE_CRUD_CHARGER_INIT = 'UPDATE_CRUD_CHARGER_INIT';
export const UPDATE_CRUD_CHARGER_SUCCESS = 'UPDATE_CRUD_CHARGER_SUCCESS';
export const UPDATE_CRUD_CHARGER_FAILURE = 'SAVE_CRUD_CHARGER_FAILURE';

export const FETCH_LIST_CRUD_CHARGER_ID_INIT =
  ' FETCH_LIST_CRUD_CHARGER_ID_INIT';
export const FETCH_LIST_CRUD_CHARGER_ID_SUCCESS =
  ' FETCH_LIST_CRUD_CHARGER_ID_SUCCESS';
export const FETCH_LIST_CRUD_CHARGER_ID_FAILURE =
  'FETCH_LIST_CRUD_CHARGER_ID_FAILURE';
