export const RESET_CRUD_DEVICE_UPDATE = 'RESET_CRUD_DEVICE_UPDATE';
export const RESET_MODAL_CRUD_DEVICE_UPDATE = 'RESET_MODAL_CRUD_DEVICE_UPDATE';

/* (ASYNC) */
export const UPDATE_CRUD_DEVICE_INIT = 'UPDATE_CRUD_DEVICE_INIT';
export const UPDATE_CRUD_DEVICE_SUCCESS = 'UPDATE_CRUD_DEVICE_SUCCESS';
export const UPDATE_CRUD_DEVICE_FAILURE = 'SAVE_CRUD_DEVICE_FAILURE';

export const FETCH_LIST_CRUD_DEVICE_ID_INIT = ' FETCH_LIST_CRUD_DEVICE_ID_INIT';
export const FETCH_LIST_CRUD_DEVICE_ID_SUCCESS =
  ' FETCH_LIST_CRUD_DEVICE_ID_SUCCESS';
export const FETCH_LIST_CRUD_DEVICE_ID_FAILURE =
  'FETCH_LIST_CRUD_DEVICE_ID_FAILURE';
