export const RESET_CRUD_CHARGER = 'RESET_CRUD_CHARGER';
export const RESET_MODAL_CRUD_CHARGER_ADD = 'RESET_MODAL_CRUD_CHARGER_ADD';

/* (ASYNC) */
export const SAVE_CRUD_CHARGER_INIT = 'SAVE_CRUD_CHARGER_INIT';
export const SAVE_CRUD_CHARGER_SUCCESS = 'SAVE_CRUD_CHARGER_SUCCESS';
export const SAVE_CRUD_CHARGER_FAILURE = 'SAVE_CRUD_CHARGER_FAILURE';
