/* Datos Async */
export const FETCH_CRUD_LIST_DEVICE_INIT = 'FETCH_CRUD_LIST_DEVICE_INIT';
export const FETCH_CRUD_LIST_DEVICE_SUCCESS = 'FETCH_CRUD_LIST_DEVICE_SUCCESS';
export const FETCH_CRUD_LIST_DEVICE_FAILURE = 'FETCH_CRUD_LIST_DEVICE_FAILURE';

export const DELETE_CRUD_LIST_DEVICE_INIT = 'DELETE_CRUD_LIST_DEVICE_INIT';
export const DELETE_CRUD_LIST_DEVICE_SUCCESS =
  'DELETE_CRUD_LIST_DEVICE_SUCCESS';
export const DELETE_CRUD_LIST_DEVICE_FAILURE =
  'DELETE_CRUD_LIST_DEVICE_FAILURE';

export const RESET_CRUD_LIST_DEVICE = 'RESET_CRUD_LIST_DEVICE';
export const RESET_MODAL_CRUD_DEVICE_DELETE = 'RESET_MODAL_CRUD_DEVICE_DELETE';
