export const RESET_CRUD_FLEET = 'RESET_CRUD_FLEET';
export const RESET_MODAL_CRUD_FLEET_ADD = 'RESET_MODAL_CRUD_FLEET_ADD';

/* (ASYNC) */
export const SAVE_CRUD_FLEET_INIT = 'SAVE_CRUD_FLEET_INIT';
export const SAVE_CRUD_FLEET_SUCCESS = 'SAVE_CRUD_FLEET_SUCCESS';
export const SAVE_CRUD_FLEET_FAILURE = 'SAVE_CRUD_FLEET_FAILURE';
