/* Datos Async */
export const FETCH_COP25_REINA_INIT = 'FETCH_COP25_REINA_INIT';
export const FETCH_COP25_REINA_SUCCESS = 'FETCH_COP25_REINA_SUCCESS';
export const FETCH_COP25_REINA_FAILURE = 'FETCH_COP25_REINA_FAILURE';

export const RESET_COP25_REINA = 'RESET_COP25_REINA';
