/* Datos Async */
export const FETCH_CRUD_LIST_CHARGER_INIT = 'FETCH_CRUD_LIST_CHARGER_INIT';
export const FETCH_CRUD_LIST_CHARGER_SUCCESS =
  'FETCH_CRUD_LIST_CHARGER_SUCCESS';
export const FETCH_CRUD_LIST_CHARGER_FAILURE =
  'FETCH_CRUD_LIST_CHARGER_FAILURE';

export const DELETE_CRUD_LIST_CHARGER_INIT = 'DELETE_CRUD_LIST_CHARGER_INIT';
export const DELETE_CRUD_LIST_CHARGER_SUCCESS =
  'DELETE_CRUD_LIST_CHARGER_SUCCESS';
export const DELETE_CRUD_LIST_CHARGER_FAILURE =
  'DELETE_CRUD_LIST_CHARGER_FAILURE';

export const RESET_CRUD_LIST_CHARGER = 'RESET_CRUD_LIST_CHARGER';
export const RESET_MODAL_CRUD_CHARGER_DELETE =
  'RESET_MODAL_CRUD_CHARGER_DELETE';
