export const RESET_CRUD_DRIVER = 'RESET_CRUD_DRIVER';
export const RESET_MODAL_CRUD_DRIVER_ADD = 'RESET_MODAL_CRUD_DRIVER_ADD';

/* (ASYNC) */
export const SAVE_CRUD_DRIVER_INIT = 'SAVE_CRUD_DRIVER_INIT';
export const SAVE_CRUD_DRIVER_SUCCESS = 'SAVE_CRUD_DRIVER_SUCCESS';
export const SAVE_CRUD_DRIVER_FAILURE = 'SAVE_CRUD_DRIVER_FAILURE';
