export const RESET_CRUD_DRIVER_UPDATE = 'RESET_CRUD_DRIVER_UPDATE';
export const RESET_MODAL_CRUD_DRIVER_UPDATE = 'RESET_MODAL_CRUD_DRIVER_UPDATE';

/* (ASYNC) */
export const UPDATE_CRUD_DRIVER_INIT = 'UPDATE_CRUD_DRIVER_INIT';
export const UPDATE_CRUD_DRIVER_SUCCESS = 'UPDATE_CRUD_DRIVER_SUCCESS';
export const UPDATE_CRUD_DRIVER_FAILURE = 'SAVE_CRUD_DRIVER_FAILURE';

export const FETCH_LIST_CRUD_DRIVER_ID_INIT = ' FETCH_LIST_CRUD_DRIVER_ID_INIT';
export const FETCH_LIST_CRUD_DRIVER_ID_SUCCESS =
  ' FETCH_LIST_CRUD_DRIVER_ID_SUCCESS';
export const FETCH_LIST_CRUD_DRIVER_ID_FAILURE =
  'FETCH_LIST_CRUD_DRIVER_ID_FAILURE';
