/* Datos Async */
export const FETCH_DEVICE_FILTER_INIT = 'FETCH_DEVICE_FILTER_INIT';
export const FETCH_DEVICE_FILTER_SUCCESS = 'FETCH_DEVICE_FILTER_SUCCESS';
export const FETCH_DEVICE_FILTER_FAILURE = 'FETCH_DEVICE_FILTER_FAILURE';

export const FETCH_MODELS_FILTER_INIT = 'FETCH_MODELS_FILTER_INIT';
export const FETCH_MODELS_FILTER_SUCCESS = 'FETCH_MODELS_FILTER_SUCCESS';
export const FETCH_MODELS_FILTER_FAILURE = 'FETCH_MODELS_FILTER_FAILURE';

export const FETCH_TYPES_FILTER_INIT = 'FETCH_TYPES_FILTER_INIT';
export const FETCH_TYPES_FILTER_SUCCESS = 'FETCH_TYPES_FILTER_SUCCESS';
export const FETCH_TYPES_FILTER_FAILURE = 'FETCH_TYPES_FILTER_FAILURE';

export const FETCH_FLEET_FILTER_INIT = 'FETCH_FLEET_FILTER_INIT';
export const FETCH_FLEET_FILTER_SUCCESS = 'FETCH_FLEET_FILTER_SUCCESS';
export const FETCH_FLEET_FILTER_FAILURE = 'FETCH_FLEET_FILTER_FAILURE';
