/* Datos Async */
export const FETCH_CRUD_AREA_TURNOS_INIT = 'FETCH_CRUD_AREA_TURNOS_INIT';
export const FETCH_CRUD_AREA_TURNOS_SUCCESS = 'FETCH_CRUD_AREA_TURNOS_SUCCESS';
export const FETCH_CRUD_AREA_TURNOS_FAILURE = 'FETCH_CRUD_AREA_TURNOS_FAILURE';

export const RESET_CRUD_HOME = 'RESET_CRUD_HOME';
