/* Datos Async */
export const FETCH_CRUD_AREA_TURNOS_INIT = 'FETCH_CRUD_AREA_TURNOS_INIT';
export const FETCH_CRUD_AREA_TURNOS_SUCCESS = 'FETCH_CRUD_AREA_TURNOS_SUCCESS';
export const FETCH_CRUD_AREA_TURNOS_FAILURE = 'FETCH_CRUD_AREA_TURNOS_FAILURE';

export const FETCH_CRUD_TORTAS_INIT = 'FETCH_CRUD_TORTAS_INIT';
export const FETCH_CRUD_TORTAS_SUCCESS = 'FETCH_CRUD_TORTAS_SUCCESS';
export const FETCH_CRUD_TORTAS_FAILURE = 'FETCH_CRUD_TORTAS_FAILURE';

export const FETCH_CRUD_TURNOS_MAS_RIESGOSOS_INIT =
  'FETCH_CRUD_TURNOS_MAS_RIESGOSOS_INIT';
export const FETCH_CRUD_TURNOS_MAS_RIESGOSOS_SUCCESS =
  'FETCH_CRUD_TURNOS_MAS_RIESGOSOS_SUCCESS';
export const FETCH_CRUD_TURNOS_MAS_RIESGOSOS_FAILURE =
  'FETCH_CRUD_TURNOS_MAS_RIESGOSOS_FAILURE';

export const FETCH_CRUD_GRAPH_INIT = 'FETCH_CRUD_GRAPH_INIT';
export const FETCH_CRUD_GRAPH_SUCCESS = 'FETCH_CRUD_GRAPH_SUCCESS';
export const FETCH_CRUD_GRAPH_FAILURE = 'FETCH_CRUD_GRAPH_FAILURE';

export const FETCH_CRUD_TABLE_INIT = 'FETCH_CRUD_TABLE_INIT';
export const FETCH_CRUD_TABLE_SUCCESS = 'FETCH_CRUD_TABLE_SUCCESS';
export const FETCH_CRUD_TABLE_FAILURE = 'FETCH_CRUD_TABLE_FAILURE';

export const RESET_CRUD_HOME = 'RESET_CRUD_HOME';
export const RESET_HOME_FILTER = 'RESET_HOME_FILTER';
