/* Datos Async */
export const FETCH_CRUD_LIST_VEHICLE_INIT = 'FETCH_CRUD_LIST_VEHICLE_INIT';
export const FETCH_CRUD_LIST_VEHICLE_SUCCESS =
  'FETCH_CRUD_LIST_VEHICLE_SUCCESS';
export const FETCH_CRUD_LIST_VEHICLE_FAILURE =
  'FETCH_CRUD_LIST_VEHICLE_FAILURE';

export const DELETE_CRUD_LIST_VEHICLE_INIT = 'DELETE_CRUD_LIST_VEHICLE_INIT';
export const DELETE_CRUD_LIST_VEHICLE_SUCCESS =
  'DELETE_CRUD_LIST_VEHICLE_SUCCESS';
export const DELETE_CRUD_LIST_VEHICLE_FAILURE =
  'DELETE_CRUD_LIST_VEHICLE_FAILURE';

export const RESET_CRUD_LIST_VEHICLE = 'RESET_CRUD_LIST_VEHICLE';
export const RESET_MODAL_CRUD_VEHICLE_DELETE =
  'RESET_MODAL_CRUD_VEHICLE_DELETE';
