/* Datos Async */
export const FETCH_CRUD_LIST_FLEET_INIT = 'FETCH_CRUD_LIST_FLEET_INIT';
export const FETCH_CRUD_LIST_FLEET_SUCCESS = 'FETCH_CRUD_LIST_FLEET_SUCCESS';
export const FETCH_CRUD_LIST_FLEET_FAILURE = 'FETCH_CRUD_LIST_FLEET_FAILURE';

export const DELETE_CRUD_LIST_FLEET_INIT = 'DELETE_CRUD_LIST_FLEET_INIT';
export const DELETE_CRUD_LIST_FLEET_SUCCESS = 'DELETE_CRUD_LIST_FLEET_SUCCESS';
export const DELETE_CRUD_LIST_FLEET_FAILURE = 'DELETE_CRUD_LIST_FLEET_FAILURE';

export const RESET_CRUD_LIST_FLEET = 'RESET_CRUD_LIST_FLEET';
export const RESET_MODAL_CRUD_FLEET_DELETE = 'RESET_MODAL_CRUD_FLEET_DELETE';
