export const RESET_CRUD_VEHICLE = 'RESET_CRUD_VEHICLE';
export const RESET_MODAL_CRUD_VEHICLE_ADD = 'RESET_MODAL_CRUD_VEHICLE_ADD';

/* (ASYNC) */
export const SAVE_CRUD_VEHICLE_INIT = 'SAVE_CRUD_VEHICLE_INIT';
export const SAVE_CRUD_VEHICLE_SUCCESS = 'SAVE_CRUD_VEHICLE_SUCCESS';
export const SAVE_CRUD_VEHICLE_FAILURE = 'SAVE_CRUD_VEHICLE_FAILURE';
