/* Datos Async */
export const FETCH_MAPA_INIT = 'FETCH_MAPA_INIT';
export const FETCH_MAPA_SUCCESS = 'FETCH_MAPA_SUCCESS';
export const FETCH_MAPA_FAILURE = 'FETCH_MAPA_FAILURE';

export const FETCH_MAPA_VEHICLE_INIT = 'FETCH_MAPA_VEHICLE_INIT';
export const FETCH_MAPA_VEHICLE_SUCCESS = 'FETCH_MAPA_VEHICLE_SUCCESS';
export const FETCH_MAPA_VEHICLE_FAILURE = 'FETCH_MAPA_VEHICLE_FAILURE';

export const FETCH_MAPA_DEVICE_INIT = 'FETCH_MAPA_DEVICE_INIT';
export const FETCH_MAPA_DEVICE_SUCCESS = 'FETCH_MAPA_DEVICE_SUCCESS';
export const FETCH_MAPA_DEVICE_FAILURE = 'FETCH_MAPA_DEVICE_FAILURE';

export const RESET_MAPA = 'RESET_MAPA';
export const RESET_MODAL_MAPA = 'RESET_MODAL_MAPA';

export const FETCH_MAPA_VEHICLE_GRAPH_INIT = 'FETCH_MAPA_VEHICLE_GRAPH_INIT';
export const FETCH_MAPA_VEHICLE_GRAPH_SUCCESS =
  'FETCH_MAPA_VEHICLE_GRAPH_SUCCESS';
export const FETCH_MAPA_VEHICLE_GRAPH_FAILURE =
  'FETCH_MAPA_VEHICLE_GRAPH_FAILURE';
