/* Datos Async */
export const FETCH_CRUD_LIST_DRIVER_INIT = 'FETCH_CRUD_LIST_DRIVER_INIT';
export const FETCH_CRUD_LIST_DRIVER_SUCCESS = 'FETCH_CRUD_LIST_DRIVER_SUCCESS';
export const FETCH_CRUD_LIST_DRIVER_FAILURE = 'FETCH_CRUD_LIST_DRIVER_FAILURE';

export const DELETE_CRUD_LIST_DRIVER_INIT = 'DELETE_CRUD_LIST_DRIVER_INIT';
export const DELETE_CRUD_LIST_DRIVER_SUCCESS =
  'DELETE_CRUD_LIST_DRIVER_SUCCESS';
export const DELETE_CRUD_LIST_DRIVER_FAILURE =
  'DELETE_CRUD_LIST_DRIVER_FAILURE';

export const RESET_CRUD_LIST_DRIVER = 'RESET_CRUD_LIST_DRIVER';
export const RESET_MODAL_CRUD_DRIVER_DELETE = 'RESET_MODAL_CRUD_DRIVER_DELETE';
