export const RESET_CRUD_VEHICLE_UPDATE = 'RESET_CRUD_VEHICLE_UPDATE';
export const RESET_MODAL_CRUD_VEHICLE_UPDATE =
  'RESET_MODAL_CRUD_VEHICLE_UPDATE';

/* (ASYNC) */
export const UPDATE_CRUD_VEHICLE_INIT = 'UPDATE_CRUD_VEHICLE_INIT';
export const UPDATE_CRUD_VEHICLE_SUCCESS = 'UPDATE_CRUD_VEHICLE_SUCCESS';
export const UPDATE_CRUD_VEHICLE_FAILURE = 'SAVE_CRUD_VEHICLE_FAILURE';

export const FETCH_LIST_CRUD_VEHICLE_ID_INIT =
  ' FETCH_LIST_CRUD_VEHICLE_ID_INIT';
export const FETCH_LIST_CRUD_VEHICLE_ID_SUCCESS =
  ' FETCH_LIST_CRUD_VEHICLE_ID_SUCCESS';
export const FETCH_LIST_CRUD_VEHICLE_ID_FAILURE =
  'FETCH_LIST_CRUD_VEHICLE_ID_FAILURE';
