export const RESET_CRUD_FLEET_UPDATE = 'RESET_CRUD_FLEET_UPDATE';
export const RESET_MODAL_CRUD_FLEET_UPDATE = 'RESET_MODAL_CRUD_FLEET_UPDATE';

/* (ASYNC) */
export const UPDATE_CRUD_FLEET_INIT = 'UPDATE_CRUD_FLEET_INIT';
export const UPDATE_CRUD_FLEET_SUCCESS = 'UPDATE_CRUD_FLEET_SUCCESS';
export const UPDATE_CRUD_FLEET_FAILURE = 'SAVE_CRUD_FLEET_FAILURE';

export const FETCH_LIST_CRUD_FLEET_ID_INIT = ' FETCH_LIST_CRUD_FLEET_ID_INIT';
export const FETCH_LIST_CRUD_FLEET_ID_SUCCESS =
  ' FETCH_LIST_CRUD_FLEET_ID_SUCCESS';
export const FETCH_LIST_CRUD_FLEET_ID_FAILURE =
  'FETCH_LIST_CRUD_FLEET_ID_FAILURE';
