export const RESET_CRUD_DEVICE = 'RESET_CRUD_DEVICE';
export const RESET_MODAL_CRUD_DEVICE_ADD = 'RESET_MODAL_CRUD_DEVICE_ADD';

/* (ASYNC) */
export const SAVE_CRUD_DEVICE_INIT = 'SAVE_CRUD_DEVICE_INIT';
export const SAVE_CRUD_DEVICE_SUCCESS = 'SAVE_CRUD_DEVICE_SUCCESS';
export const SAVE_CRUD_DEVICE_FAILURE = 'SAVE_CRUD_DEVICE_FAILURE';
